### ISSUE TITLE
Can't add plugins

### ISSUE THREAD

**Issue by albertkim** [PhilippHeuer/wordpress-heroku#12]
### Description of your issue
After installation, there is no option to add a plugin under the `Plugins` tab.

### Steps to Reproduce
1) Install
2) Click `Plugins`

![image](https://user-images.githubusercontent.com/5528625/31057092-b637d124-a691-11e7-93ed-02edf98df8a5.png)

### Other Information 
Git Commit/Version:

**Comment by PhilippHeuer** [comment]
The Filesystem on Heroku isn't persistent - you can't install plugins at runtime when you host on Heroku.

Therefore you need to install your plugins before you deploy - either manually by placing it in `web/app/plugins` folder or using the composer.json.

Take a look at the wiki:
https://github.com/PhilippHeuer/wordpress-heroku/wiki/WordPress---Plugins---Themes

**Comment by albertkim** [comment]
Cool, thank you for the explanation!
