### ISSUE TITLE
WordPress 4.8

### ISSUE THREAD

**Issue by mattheworres** [PhilippHeuer/wordpress-heroku#13]
### Description of your issue
When's 4.8 coming down the pike?

### Steps to Reproduce
...

### Other Information 
I see you're working on it in the develop branch, but wanted to know if you had a good idea for when that's coming down the pike.

Looks like the official WordPress milestone has 4.9 set to release in November, too.

Great job on this library, VERY helpful!!

**Comment by PhilippHeuer** [comment]
It already is ;)

The current wordpress version in the repository is `4.8.1`. But i will update it to `4.8.2` within the next few days.

**Comment by mattheworres** [comment]
Oh, awesome. My bad - for some reason I thought it was 4.7
