### ISSUE TITLE
Changing Buildpack

### ISSUE THREAD

**Issue by jpdjere** [PhilippHeuer/wordpress-heroku#18]
If I fork this repo so as to do the One-Click-Deployment  but changing files, is there a way to change the buildpack? I see there is a .buildpack file where `https://github.com/heroku/heroku-buildpack-php`is defined. But where is the Bedrock buildpack defined (with all the WP files)?

I would like to clone that buildpack and point this project to my (modified) fork. Is it possible?

Thanks

**Comment by PhilippHeuer** [comment]
There is no bedrock/wordpress buildpack used (not sure if one exists), when you deploy the application the php buildpack detects the `composer.json` and installs all specified dependencies (including wordpress 4.x)

This allows me to upgrade wordpress really simple just by changing the version number in the `composer.json`.

**Comment by jpdjere** [comment]
Thanks for your answer @PhilippHeuer !
