### ISSUE TITLE
Wordfence could not get an API key from the Wordfence scanning servers when it activated

### ISSUE THREAD

**Issue by ahmadchoirunnajib** [PhilippHeuer/wordpress-heroku#19]
Wordfence could not get an API key from the Wordfence scanning servers when it activated. You can try to fix this by going to the Wordfence "options" page and hitting "Save Changes". This will cause Wordfence to retry fetching an API key for you. If you keep seeing this error it usually means your WordPress server can't connect to our scanning servers. You can try asking your WordPress host to allow your WordPress server to connect to noc1.wordfence.com.

Can i resolve this?

**Comment by PhilippHeuer** [comment]
Can you descripbe your issue in more detail? I can't replicate it right now.

When i enter the api key in the options and save it works fine - i tested it on a new instane i deployed on heroku according to the readme.
