### ISSUE TITLE
Wp-admin password

### ISSUE THREAD

**Issue by smlc** [PhilippHeuer/wordpress-heroku#20]
### Description of your issue
How can I set the password of the wp-admin ?

### Other Information 
Git Commit/Version:

**Comment by PhilippHeuer** [comment]
If you fill the field `HEROKU_APP_NAME` then it generates a random password, make sure that the `HEROKU_APP_NAME` field is empty.

Then you will get the default wordpress  setup page asking you to create the admin account.

**Comment by smlc** [comment]
Thanks for the response.
