### ISSUE TITLE
Can't run wp-cli server locally

### ISSUE THREAD

**Issue by kenziebottoms** [PhilippHeuer/wordpress-heroku#24]
### Description of your issue
When I run `php wp-cli.phar server --host=localhost --port=80` in the root of my project, I get this:

```Directory <project root>/web/wp does not exist.```

### Steps to Reproduce
I just forked this repo and tried to follow the [Deployment - Local](https://github.com/PhilippHeuer/wordpress-heroku/wiki/Deployment) instructions. Here's the pertinent part of my `.env` file:
```# DB Connection
# the db, db user, and db pw are all the same
CUSTOM_DB_URL=mysql://second_stage:second_stage@localhost:3306/second_stage

# WP Settings 
WP_ENV=development
WP_HOME=http://localhost
WP_SITEURL=${WP_HOME}/wp
```

### Other Information 
I'm running PHP 7.0.22 and have the latest version of WP CLI (can't find the number).

**Comment by PhilippHeuer** [comment]
You need to run `composer install` locally so that the dependencies will be installed. This also installs wordpress 4.9.2 into `/web/wp`.

I have added this step to the wiki page.

**Comment by kenziebottoms** [comment]
Thanks so much!
