### ISSUE TITLE
Some key can't parse correctly AWS_S3_URL

### ISSUE THREAD

**Issue by naoa** [PhilippHeuer/wordpress-heroku#26]
### Description of your issue
You are using ``parse_url`` function to parse AWS_S3 options.

https://github.com/PhilippHeuer/wordpress-heroku/blob/master/config/plugins/wordpress/wordpress-s3uploads.php#L7

But it can't parse correctly some key included "\n".

### Steps to Reproduce
For example, the following string can't parse_url correctly.

```php
<?php
  $env = "s3://hoge:hoge/nhoge@s3-us-west-2.amazonaws.com/backetName";
  var_dump(parse_url($env));
?>
```

### Other Information 
Git Commit/Version: 564770e29c4182a02690b2347b9e27bb7cb4b9f8

**Comment by PhilippHeuer** [comment]
Hey, thanks for contributing 👍

I guess i was just lucky with my keys.
