### ISSUE TITLE
More languages  [SOLVED]

### ISSUE THREAD

**Issue by sbtgE** [PhilippHeuer/wordpress-heroku#31]
I would like to know how can I add more languages to my wordpress installation on heroku. Thank you very much for ur answer!

**Comment by sbtgE** [comment]
I am looking for something free, I have tried qTranslate but there was an error : "/app/web/app/languages" can you help me with this issue? Can you give me another advice, maybe another plugin. Is there a solution to upload another mo/po files to your heroku wp installation? I am looking for really easy solution but I am struggling with this issuse for eternity :/ Thank you for your help!

**Comment by PhilippHeuer** [comment]
you can get qtranslate to work, but heroku has a kinda of temporary filesystem, so you can't write to it - for the same reason media uploads dont work.

There are 2 deployment examples in the wiki - you need to follow the custom one.

You need to download the files of `/app/web/app/language` from some other source and commit them into your repository before you push to heroku.

**Comment by sbtgE** [comment]
Thank you very much, it works perfectly if I upload it manually.
