### ISSUE TITLE
how to upload my own theme & plugin not exist as public ?

### ISSUE THREAD

**Issue by todokku** [PhilippHeuer/wordpress-heroku#37]
Hi Philipp ,
how to upload my own theme & plugin not exist as public ?
fine regards
goodbye

**Comment by PhilippHeuer** [comment]
Theres a section about this in the wiki:

- Your custom plugins: - https://github.com/PhilippHeuer/wordpress-heroku/wiki/WordPress---Plugins---Themes#method-2-your-custom-plugins
- Your custom themes - https://github.com/PhilippHeuer/wordpress-heroku/wiki/WordPress---Plugins---Themes#method-2-your-custom-themes
